version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: sample_rails6_app_production
       MYSQL_USER: sample_rails6_app
       MYSQL_PASSWORD: apppass

   web:
     depends_on:
       - db
     image: rubyapp:latest
     ports:
       - "80:3000"
     restart: always
     environment:
       RAILS_ENV: production
       SECRET_KEY_BASE: secret
       DB_USERNAME: sample_rails6_app
       DB_PASSWORD: apppass
       DB_DATABASE: sample_rails6_app_production
       DB_PORT: 3306
       DB_HOST: db
       RAILS_MAX_THREADS: 5

volumes:
    db_data:
